### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by joshunger** [CircleCI-Public/aws-cli-orb#1]
`config.yml`

```
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - aws-s3/copy:
...
```

```
    ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by joshunger** [comment]
This fixed the issue -

```
    steps:
      - run: sudo apt-get install python-dev
      - aws-s3/copy:
...
```
