### ISSUE TITLE
Can’t figure out how to write a valid aws-cli/configure step with parameters

### ISSUE THREAD

**Issue by perbergland** [CircleCI-Public/aws-cli-orb#10]
I assume it's just my poor yaml skills but I can't get this to work.

This does work:
```
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

build-docker:
    machine: true
    steps:
      - aws-cli/install
      - aws-cli/configure
```
but as soon as I add parameters, I get schema failures

```
build-docker:
    machine: true
    steps:
      - aws-cli/install
      - aws-cli/configure:
        aws-access-key-id: AWS_ECR_USER_KEY
        aws-secret-access-key: AWS_ECR_USER_SECRET
        aws-region: AWS_DEFAULT_REGION
```

```
$ circleci config process .circleci/config.yml

Error: ERROR IN CONFIG FILE:
[#/jobs/build-docker] 0 subschemas matched instead of one
1. [#/jobs/build-docker] only 1 subschema matches out of 2
|   1. [#/jobs/build-docker/steps/4] 0 subschemas matched instead of one
|   |   1. [#/jobs/build-docker/steps/4] expected type: String, found: Mapping
|   |   |   Shorthand commands, like `checkout`
|   |   |   SCHEMA:
|   |   |     type: string
|   |   |   INPUT:
|   |   |     configure: null
|   |   |     aws-access-key-id: AWS_ECR_USER_KEY
|   |   |     aws-secret-access-key: AWS_ECR_USER_SECRET
|   |   |     aws-region: AWS_DEFAULT_REGION
|   |   2. [#/jobs/build-docker/steps/4] maximum size: [1], found: [3]
|   |   |   long form commands like `run:`
|   |   |   SCHEMA:
|   |   |     maxProperties: 1
|   |   |   INPUT:
|   |   |     configure: null
|   |   |     aws-access-key-id: AWS_ECR_USER_KEY
|   |   |     aws-secret-access-key: AWS_ECR_USER_SECRET
|   |   |     aws-region: AWS_DEFAULT_REGION
2. [#/jobs/build-docker] expected type: String, found: Mapping
|   Job may be a string reference to another job
