### ISSUE TITLE
Add parameter to enable branch level filtering

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/aws-cli-orb#11]
Use case is a job that pushes to multiple registries, but selection is based on branch.

Using multiple jobs and branch filtering is not applicable since it requires docker image to be passed which is slow and expensive.

Since config just calls orb, bash logic cant be used.  This should essentally add that bash logic to the install commands.

**Comment by eddiewebb** [comment]
Instead of making this a concern of every orb, I have asked Product team for considerations and there is some step-level filtering and other potential changes to make this a universal pattern in the future.

For now @iynere pointed out t[his great command in our build-tools orb](https://github.com/CircleCI-Public/build-tools-orb/blob/master/src/commands/run-filtered.yml).

```
orbs:
  build-tools: circleci/build-tools@2.2.0
jobs:
  my_job:
    machine:
      image: circleci/classic:latest
    steps:
    - build-tools/run-filtered:
       only-branch: master
       steps:
        - aws/install
        - aws/configure
        - aws/push
    - run: echo "This step always runs"

      
```
