### ISSUE TITLE
aws: command not found?

### ISSUE THREAD

**Issue by paarth1995** [CircleCI-Public/aws-cli-orb#120]
I am using the `aws-code-deploy` orb in conjunction with `aws-cli` orb to deploy an application to ECS. This is what my config.yml looks like :- 

```
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
  aws-code-deploy: circleci/aws-code-deploy@2.0.0
jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - aws-code-deploy/deploy-bundle:
          application-name: "blue-green"
          bundle-bucket: "blue-green-cd-ls"
          bundle-key: "appspec.yml"
          deployment-group: "blue-green-ls"
          bundle-type: "yaml"
workflows:
  build-and-deploy:
    jobs:
      - deploy
```

but i keep running into `/bin/bash: line 6: aws: command not found`. Please see the complete ouput :- 

```
#!/bin/bash -eo pipefail
ID=$(aws deploy create-deployment \
        --application-name blue-green \
        --deployment-group-name blue-green-ls \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --s3-location bucket=blue-green-cd-ls,bundleType=yaml,key=appspec.yml.yaml \
        --output text \
        --query '[deploymentId]')
STATUS=$(aws deploy get-deployment \
          --deployment-id $ID \
          --output text \
          --query '[deploymentInfo.status]')
while [[ $STATUS == "Created" || $STATUS == "InProgress" || $STATUS == "Pending" || $STATUS == "Queued" || $STATUS == "Ready" ]]; do
  echo "Status: $STATUS..."
  STATUS=$(aws deploy get-deployment \
            --deployment-id $ID \
            --output text \
            --query '[deploymentInfo.status]')
  sleep 5
done
if [[ $STATUS == "Succeeded" ]]; then
  EXITCODE=0
  echo "Deployment finished."
else
  EXITCODE=1
  echo "Deployment failed!"
fi
aws deploy get-deployment --deployment-id $ID
exit $EXITCODE

/bin/bash: line 6: aws: command not found

Exited with code exit status 127
CircleCI received exit code 127
```

**Comment by paarth1995** [comment]
Updated config to fix the issue :- 

```

version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
  aws-code-deploy: circleci/aws-code-deploy@2.0.0
jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - aws-code-deploy/deploy-bundle:
          application-name: "blue-green"
          bundle-bucket: "blue-green-cd-ls"
          bundle-key: "appspec"
          deployment-group: "blue-green-ls"
          bundle-type: "yaml"
workflows:
  build-and-deploy:
    jobs:
      - deploy
```
