### ISSUE TITLE
aws-cli/setup for multiple profiles clobbers default region non-obviously

### ISSUE THREAD

**Issue by r4v5** [CircleCI-Public/aws-cli-orb#121]
If you create two AWS profiles:
```yaml

  - aws-cli/setup:
      profile-name: artifactory
      aws-region: VAR_THAT_RESOLVES_TO_EU_CENTRAL_1
  - aws-cli/setup:
      profile-name: deployer
      aws-region: VAR_THAT_RESOLVES_TO_US_EAST_2
```

The end result will be a ~/.aws/config that looks like:
```ini
[default]
region = us-east-2
[profile artifactory]
region = eu-central-1
[profile deployer]
region = us-east-2
```

If you set them up in the reverse order, the `default` profile ends up with region `eu-central-1`.

The help text for the "configure default region" parameter is ambiguous as to whether this is intended:

```yaml
  configure-default-region:
    default: true
    description: >
      Some AWS actions don't require a region; set this to false if you do not
      want to store a default region in ~/.aws/config
```

"default region" could be reasonably construed to be the default region _for the profile_, especially given likelihood of conflation with the use of environment variables `$AWS_REGION` and `$AWS_DEFAULT_REGION`. The fact that [the source for the option](https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/scripts/configure.sh#L31) currently includes a `--profile` flag reinforces that idea. However, because the value is `default.region`, it's overriding the setting outside the profile.

It would be more helpful if that help text mentioned setting the default _profile's_ region and not the default region, and the command didn't include the `--profile` flag.

(Incidentally, the option existing at all was quite helpful for figuring out why this multi-region deployment code isn't working.)
