### ISSUE TITLE
aws-cli/setup does not work on a Windows executor

### ISSUE THREAD

**Issue by theouteredge** [CircleCI-Public/aws-cli-orb#125]
I'm getting the following error when trying to install the aws cli on a windows machine build:

```
orbs:
  docker: circleci/docker@2.1.4
  aws-cli: circleci/aws-cli@3.1
  win: circleci/windows@5.0.0

jobs:
  build-serverAgent:
    executor:
      name: win/default
    resource_class: xlarge
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
```

Error:
```
At line:1 char:3
+ if cat /etc/issue | grep "Alpine" >/dev/null 2>&1; then
+   ~
Missing '(' after 'if' in if statement.
At line:2 char:7
+     if [ "$ID" = 0 ]; then export SUDO=""; else export SUDO="sudo"; f ...
+       ~
Missing '(' after 'if' in if statement.
At line:2 char:9
+     if [ "$ID" = 0 ]; then export SUDO=""; else export SUDO="sudo"; f ...
+         ~
Missing type name after '['.
At line:4 char:7
+     if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo" ...
+       ~
Missing '(' after 'if' in if statement.
At line:4 char:9
+     if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo" ...
+         ~
Missing type name after '['.
At line:7 char:17
+ Install_AWS_CLI() {
+                 ~
An expression was expected after '('.
At line:9 char:13
+     cd /tmp || exit
+             ~~
The token '||' is not a valid statement separator in this version.
At line:11 char:7
+     if uname -a | grep "Darwin"; then
+       ~
Missing '(' after 'if' in if statement.
At line:7 char:19
+ Install_AWS_CLI() {
+                   ~
Missing closing '}' in statement block or type definition.
At line:29 char:14
+     linux_x86)
+              ~
Unexpected token ')' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by theouteredge** [comment]
Got this working by changing:
```
build-serverAgent:
    executor:
      name: win/default
      shell: bash.exe
```

The for all the other commands to use
```
  -  run
      shell: powershell.exe
```
