### ISSUE TITLE
Node missing in v4.0.0

### ISSUE THREAD

**Issue by ryanwalters** [CircleCI-Public/aws-cli-orb#135]
After upgrading from `circleci/aws-cli@3.1.5` to `circleci/aws-cli@4.0.0`, builds are failing.

`config.yml` snippet:
```yaml
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  build-and-deploy: &build-and-deploy
    executor: aws-cli/default
    steps:
      - checkout
      - run: node --version
      - run: python --version
      - aws-cli/install
      - aws-cli/setup
      ...
```

Error message:
```bash
#!/bin/bash -eo pipefail
node --version
/bin/bash: line 1: node: command not found

Exited with code exit status 127
CircleCI received exit code 127
```

**Comment by batovpasha** [comment]
@ryanwalters Hi! Facing the same issue. It's because in the v4.0.0 `aws-cli/default` executor has switched from the [cimg/python](https://github.com/CircleCI-Public/aws-cli-orb/blob/v3.1.5/src/executors/default.yml#L11)(with default tag) image to the [cimg/base](https://github.com/CircleCI-Public/aws-cli-orb/blob/v4.0.0/src/executors/default.yml#L11) which doesn't have node pre-installed. I couldn't find a `cimg/base` tag that includes node.js, so the possible solution is to add the [node install](https://circleci.com/developer/orbs/orb/circleci/node#commands-install) command to your job.

**Comment by batovpasha** [comment]
@brivu Hello! Maybe it would be better to update the `aws-cli/default` executor description "Highly cached minimal Ubuntu docker designed for CircleCI with Python and NodeJS installed." cause currently it doesn't have NodeJS installed?

**Comment by brivu** [comment]
@batovpasha, thanks for the catching that. I'll make the changes. 
 
I'm huddling up with the team to see if we can add a `node` executor as well since so many folks seem to be using it.

**Comment by batovpasha** [comment]
@brivu thank you for looking. Are there any considerations for returning to the `cimg/python` base image with the `3.9-node` default tag?

**Comment by brivu** [comment]
Hey everyone! 

After consulting with the team, we're going to keep the default executor using the `cimg/base` docker image as it's the most widely used. 

As a work around, you can define an executor with the `executor` key in your `config.yml` file.

For example, in @ryanwalters's case you can do:
```
executors:
  node:
    docker:
      - image: cimg/node:20.3.0
```
 and the job would look like this: 
```
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
**executors:
  node:
    docker:
      - image: cimg/node:20.3.0**
jobs:
  build-and-deploy: &build-and-deploy
    executor: **node**
    steps:
      - checkout
      - run: node --version
      - run: python --version
      - aws-cli/install
      - aws-cli/setup
      ...
```

@batovpasha - in your case you can define the executor in your `config` like below: 
```
executors:
  python-node:
    docker:
      - image: cimg/python:3.0-node
```

For reference, you can find information on all of our images here including tags and variants here: 
https://circleci.com/developer/images


Hope that helps!
