### ISSUE TITLE
Why is aws-cli/setup always using AWS_SESSION_TOKEN to setup profile

### ISSUE THREAD

**Issue by krzysztofdrys** [CircleCI-Public/aws-cli-orb#139]
In my job I have two setups. First one assumes role using web identity. The second on assumes role using ENV variables. This look more or less like this:

```
  - aws-cli/setup:
      profile-name: web-identity-profile
      role-arn: << parameters.secret-role-arn >>
      role-session-name: web-identity-session-name
  - do-some-aws-work:
      profile-name: web-identity-profile
  - aws-cli/setup:
      aws-access-key-id: EKS_AWS_ACCESS_KEY_ID
      aws-secret-access-key: EKS_AWS_SECRET_ACCESS_KEY
      profile-name: profile-based-on-env
      role-arn: << parameters.secret-role-arn >>
  - do-some-aws-work:
      profile-name:  profile-based-on-env
 ````
 
 The second `do-some-aws-work` fails, with:
 ```
 An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid
```

I believe this is because the first setup setups `AWS_SESSION_TOKEN` and second setup configures profile to use `AWS_SESSION_TOKEN`:
```
        if [ -n "${AWS_SESSION_TOKEN}" ]; then
            aws configure set aws_session_token \
                "${AWS_SESSION_TOKEN}" \
                --profile "$ORB_EVAL_PROFILE_NAME"
        fi
```

Is this intended behaviour? Could execution of these lines be controlled by some job parameter?
