### ISSUE TITLE
Step 'Configure AWS Access Key ID' fails in aws-s3@1.0.11

### ISSUE THREAD

**Issue by pieterjandesmedt** [CircleCI-Public/aws-cli-orb#14]
### Orb version

circleci/aws-s3@1.0.11

See also [this issue](https://github.com/CircleCI-Public/circleci-orbs/issues/179)

### What happened

Orb step `Configure AWS Access Key ID` fails, even though step `Install AWS CLI` succeeds.

end of output of `Install AWS CLI`:
```
Running cmd: /usr/bin/python virtualenv.py --no-download --python /usr/bin/python /root/.local/lib/aws
Running cmd: /root/.local/lib/aws/bin/pip install --no-cache-dir --no-index --find-links file:///root/awscli-bundle/packages/setup setuptools_scm-1.15.7.tar.gz
Running cmd: /root/.local/lib/aws/bin/pip install --no-cache-dir --no-index --find-links file:///root/awscli-bundle/packages awscli-1.16.204.tar.gz
You can now run: /root/bin/aws --version
/root/project
```

output of `Configure AWS Access Key ID`
```
#!/bin/bash -eo pipefail
aws configure set aws_access_key_id \
$AWS_ACCESS_KEY_ID \
--profile default

/bin/bash: aws: command not found
Exited with code 127
```

Config:
```
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: node:latest
[...]
    steps:
[...]
      - run:
          name: Build
          command: npm run build
      - aws-s3/sync:
          from: dist
          to: 's3://[REDACTED]'
          arguments: '--delete'
```

### Expected behavior

It should find the `aws` command if the step just before says it's installed correctly.
