### ISSUE TITLE
When using on a Windows executor, versions are ignored

### ISSUE THREAD

**Issue by jenny-miggin** [CircleCI-Public/aws-cli-orb#157]
When using the windows executor, the AWS CLI version is unable to be updated.

### Expected behaviour

When specifying the `version` when using the `install` command, the specified version should be installed

### Actual behaviour

The version requested is ignored, and an old version of the CLI which is installed is seen as the "latest"

### Steps to reproduce

Given the below `config.yml` snippet, 

```yml
jobs:
  build:
    executor: 
      name: win/server-2019
      version: 2023.04.1
      shell: bash

    steps:
      - run:
          name: check aws cli version
          command: |
            aws --version
      - aws-cli/install:
          version: 2.12.2
```
we can see that the confirmed version that comes with windows image version `2023.04.1` is `aws-cli/1.16.209` (on `2023.08.1` is `aws-cli/2.12.0`). The result of the `install` command is:

```bash
Detected OS: Windows.
AWS CLI is already installed, skipping installation.
aws-cli/1.16.209 Python/3.6.0 Windows/10 botocore/1.12.199
```
and the version specified is not installed.
