### ISSUE TITLE
Provide a way for `assume_role_with_web_identity` to not set `AWS_*` environment variables in `BASH_ENV`

### ISSUE THREAD

**Issue by blimmer** [CircleCI-Public/aws-cli-orb#162]
## Problem Description

Today, the script always sets `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN` in `BASH_ENV`. https://github.com/CircleCI-Public/aws-cli-orb/blob/8691243cb366b71a9f73868ebd9231ba042cd3c3/src/scripts/assume_role_with_web_identity.sh#L40-L50

For workflows that only assume one role, this workflow makes sense (and should likely remain the default behavior). However, for workflows that assume multiple roles, this behavior is problematic because the last role assumed automatically "wins".

You end up with a `$BASH_ENV` that looks like this:

```bash
# From the first role assumed
export AWS_ACCESS_KEY_ID="<REDACTED>"
export AWS_SECRET_ACCESS_KEY="<REDACTED>"
export AWS_SESSION_TOKEN="<REDACTED>"
# From the second role assumed
export AWS_ACCESS_KEY_ID="<REDACTED>"
export AWS_SECRET_ACCESS_KEY="<REDACTED>"
export AWS_SESSION_TOKEN="<REDACTED>"
```

## Concrete Example

Imagine a CI job that assumes two OIDC roles:

1. `role/codeartifact` is a shared role that allows CodeArtifact access for the build process
2. `role/my-service` allows deploying the specific service

The last role that's configured will be the default role used by AWS-CLI and SDK because it'll be the credentials in `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN`.

In my case, I'd like to only configure a profile (no env variables) for the `role/codeartifact` so that it doesn't affect the rest of the environment. I'll set up CodeArtifact by specifying the profile explicitly, e.g.: `aws codeartifact get-auth-token --profile codeartifact`.

So, this would look something like this:

```yaml
- aws-cli/setup:
    profile_name: codeartifact
    role_arn: << parameters.readonly_iam_role >>
    configure_default_region: false
    configure_profile_region: true
    region: us-west-2
- run: codeartifact get-authorization-token --profile codeartifact # do not rely on env variables
```

## Suggested Fix

`aws-cli/assume_role_with_web_identity` (and other commands that call it indirectly, like `aws-cli/setup`) should accept a `configure_aws_environment_variables` boolean that defaults to `true` for backward compatibility.

From the example above, it would now look like this:

```yaml
- aws-cli/setup:
    profile_name: codeartifact
    role_arn: << parameters.readonly_iam_role >>
    configure_default_region: false
    configure_aws_environment_variables: false # <---- new setting
    configure_profile_region: true
    region: us-west-2
- run: codeartifact get-authorization-token --profile codeartifact
```

Now, I wouldn't have to worry about which order I assume the roles in.

**Comment by brivu** [comment]
Hey @blimmer, 

Thanks for opening this issue. I've been going back and forth how to handle the `assume_role_with_web_identity` command so I'm glad we have an opportunity to learn more. 

As of today, the `assume_role_with_web_identity` command only generates new temporary keys and gets exported to `$BASH_ENV`. It does not tie the keys to a specific profile, which has been causing some confusion. 

However In the `setup` command, if there is a `role_arn`,   the `assume_role_with_web_identity` command is run. Once the keys are generated, they are passed through the `configure.sh` script, which ties the keys to a specific profile by running the cli's `aws configure set` commands. That's the only reason why the keys and session token are stored as environment variables. 

The intent with the `assume_role_with_web_identity` was always to tie the generated keys to a profile so I've been considering removing the command and just consolidating it into the `setup` command (similarl to the the `configure` script)

With your suggestion, if we use `configure_aws_environment_variables: false`, the `assume_role_with_web_identity` command will essentially do nothing other than generating keys. They won't be tied to any profile nor be exported as environment variables. 

In your use case above, are you able to run the `aws-cli/setup` command twice (once for each profile)? That way, you can have a profile for your build process and one for your deploy process. When you run your build and deploy processes, you can tie the appropriate profile to each command. 

Let me know if I am missing anything! 
Brian

**Comment by blimmer** [comment]
Hi @brivu, thanks for the quick and detailed response!

In my use case, yep, I was calling `aws-cli/setup` twice. This appropriately configured the profiles, but it still left the `AWS_*` environment variables in the `$BASH_ENV`. I think I could have explicitly overridden the downstream consumer (a legacy Javascript tool that uses aws-sdk@2) to specify a profile and ignore the environment variables but, by default, it was using the environment variables, not the `default` profile.

I worked around the problem like this:

```yaml
- run: touch $BASH_ENV && cp $BASH_ENV "$BASH_ENV.bak"
- aws-cli/setup:
    profile_name: codeartifact
    role_arn: << parameters.readonly_iam_role >>
    configure_default_region: false
    configure_profile_region: true
    region: us-west-2
- run: mv "$BASH_ENV.bak" "$BASH_ENV"
- run: codeartifact get-authorization-token --profile codeartifact
```

However, it would be nice if I could somehow specify to the orb, "just create the profile, don't mess with my environment".
