### ISSUE TITLE
`install` on older windows images fails when `override_installed: true`

### ISSUE THREAD

**Issue by jenny-miggin** [CircleCI-Public/aws-cli-orb#163]
### Issue
When installing the CLI on CircleCI's Windows images, `2023.04.1` and `2022.08.1`, and the `override_installed: true` (without a version specified), the newest version of the CLI is installed, however the path fails to be updated correctly and the job fails: 

```bash
bash: aws: command not found
```

This could be down to the initial version on these images starting with 1.x, which is therefore invoking the setting of the [old path](https://github.com/CircleCI-Public/aws-cli-orb/blob/8691243cb366b71a9f73868ebd9231ba042cd3c3/src/scripts/windows/install.sh#L22) rather than the [newer path](https://github.com/CircleCI-Public/aws-cli-orb/blob/8691243cb366b71a9f73868ebd9231ba042cd3c3/src/scripts/windows/install.sh#L20) for 2.x CLI version, and could be linked to the previous expectation that `override_installed: true` was paired with a version being specified in the commands parameters. Issue does not occur on the `2023.08.1` image.

### Steps to reproduce

Use this command in a job:
```yml
jobs:
  build:
    executor: 
      name: win/server-2019
      version: 2023.04.1
      shell: bash
    steps:
      - aws-cli/install:
          override_installed: true
```
