### ISSUE TITLE
'role_arn' IS a required argument when calling 'aws-cli/setup'

### ISSUE THREAD

**Issue by Ian-Rowland-i2** [CircleCI-Public/aws-cli-orb#165]
The usage code for [configure_role_arn](https://circleci.com/developer/orbs/orb/circleci/aws-cli#usage-configure_role_arn) stipulates that you can run the following code:

```
- aws-cli/setup:
     profile_name: default
- aws-cli/role_arn_setup:
     profile_name: new-profile
     role_arn: arn:aws:iam::123456789012:role/example-role
     source_profile: default
```

i.e. the `role_arn` parameter is not required - this is borne out by the [setup command documentation](https://circleci.com/developer/orbs/orb/circleci/aws-cli#commands-setup) The idea being, presumably, that the `role_arn` is configured later using `aws-cli/role_arn_setup` (as shown in the example code above).

When the `aws-cli/setup` command is called _without_ specifying the `role_arn` , the call to `assume_role_with_web_identity` (at [line 108](https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/commands/setup.yml#L108) of the setup command) is not run.

If `assume_role_with_web_identity`  is not run then these variables are not set - `AWS_ACCESS_KEY_ID`,  `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` - in the `assume_role_with_web_identity command` [here](https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/scripts/assume_role_with_web_identity.sh#L45-L47) (which are required to authenticate with AWS).

Consequently, the call to `aws-cli/setup` fails [here](https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/scripts/configure.sh#L16) with:  

> Cannot configure profile. AWS access key id and AWS secret access key must be provided.

As borne out by the output from this failing build:

![image](https://github.com/CircleCI-Public/aws-cli-orb/assets/97098530/dc3a7c50-9ebe-40d1-b5b7-0e696a5c6719)

So the usage example for [configure_role_arn](https://circleci.com/developer/orbs/orb/circleci/aws-cli#usage-configure_role_arn) doesn't work, the documentation for [setup](https://circleci.com/developer/orbs/orb/circleci/aws-cli#commands-setup) is wrong (because `role_arn` is a required argument), and the code for the setup command needs to be corrected to remove the [when](https://circleci.com/developer/orbs/orb/circleci/aws-cli#commands-setup) condition!

It looks like the orb could benefit from better tests (ones based on actual user use cases and that verify that the examples provided  _actually_ work (on all supported platform)!

(Also the [Orb Description](https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/%40orb.yml) need to be updated as the orb now "_supports_" Windows!)

**Comment by brivu** [comment]
Hey @Ian-Rowland-i2, 

The usage example is valid assuming that you're using static `aws` keys stored as environment variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`). The `setup` will check to see if they are there and then configure them to the specified profile. 

Alternatively, you can authenticate with `OIDC` by providing the `setup` command with a valid `role-arn`. 

If neither are existent, the command will fail, which is what happened in your case. 

We already have a test for the `role_arn_setup` command that mirrors the example:
``` 
integration-test-role-arn-setup:
    executor: docker-base
    parameters:
      profile_name:
        description: Name of new profile associated with role arn.
        type: string
      role_arn:
        description: Role ARN that the profile should take.
        type: string
      source_profile:
        description: Source profile containing credentials to assume the role with role_arn.
        type: string
        default: "default"
    steps:
      - aws-cli/setup
      - aws-cli/role_arn_setup:
          profile_name: <<parameters.profile_name>>
          source_profile: <<parameters.source_profile>>
          role_arn: <<parameters.role_arn>>
```

I've also added an additional step that logs into `aws ecr` just to make sure the newly configured profile works:

```
- integration-test-role-arn-setup:
    name: integration-test-role-arn-config
    source_profile: default
    profile_name: CircleCI-Tester
    role_arn: arn:aws:iam::122211685980:role/CPE_ECR_OIDC_TEST
    context: [CPE_ORBS_AWS]
    post-steps:
      - run:
            name: Logging into ECR with new profile
            command: aws ecr get-login-password --region us-west-2 --profile "CircleCI-Tester" | docker login --username AWS --password-stdin 122211685980.dkr.ecr.us-west-2.amazonaws.com
```
