### ISSUE TITLE
circleci/aws-cli@3.1.5 fails on aws-cli/setup - Error relocating /usr/bin/curl (alpine)

### ISSUE THREAD

**Issue by colesiegel** [CircleCI-Public/aws-cli-orb#168]
`aws-cli/setup` fails on AWS CLI installer with latest version with error message `Error relocating /usr/bin/curl`, base image is running alpine linux

```
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

references:
  base_image: &base_image hashicorp/terraform:1.4.1

  working_directory: &working_directory ~/infrastructure

  default_config: &default_config
    docker:
      - image: *base_image
    working_directory: *working_directory
    environment:
      BASH_ENV: /root/.bashrc
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""

jobs:
  test:
    <<: *default_config
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: xxx
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
```

```
Installing AWS CLI v2
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
(1/4) Installing libgcc (12.2.1_git20220924-r4)
(2/4) Installing libstdc++ (12.2.1_git20220924-r4)
(3/4) Installing binutils (2.39-r2)
(4/4) Installing curl (8.3.0-r0)
Executing busybox-1.35.0-r29.trigger
OK: 34 MiB in 36 packages
Error relocating /usr/bin/curl: curl_global_trace: symbol not found

Exited with code exit status 127
```

I am able to fix it by manually updating packages and curl: 

```
apk update && apk upgrade && apk add -U curl
```
