### ISSUE TITLE
Generate shortlived AWS Keys using CircleCI OIDC token fails

### ISSUE THREAD

**Issue by ITslacker** [CircleCI-Public/aws-cli-orb#170]
I'm trying to use OIDC but it keeps failing. 

```
`version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-code-deploy: circleci/aws-code-deploy@3.0
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: Blogs
          auth:
            - aws-cli/setup:
                role-arn: $AWS_IAM_OIDC_ROLE_ARN
          bundle-bucket: $AWS_S3_BUCKET_NAME
          bundle-key: $AWS_S3_KEY
          context: $context
          deployment-group: $AWS_CODEDEPLOY_GROUP
          service-role-arn: $AWS_SERVICE_ROLE_ARN
          filters:
            branches:
              only:
                - main`
```

The error message is
![Screenshot 2023-11-09 at 1 57 24 PM](https://github.com/CircleCI-Public/aws-cli-orb/assets/62903480/ca6ee913-9bac-43de-a3b8-0b345d25cba4)
