### ISSUE TITLE
multiple calls to setup don't use newest role

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [CircleCI-Public/aws-cli-orb#178]
There may be a regression in 4.1.2.

I've used this orb in a workflow where I call it multiple times with different assumed roles:

```yml
- aws-cli/setup:
    profile_name: foo
    role_arn: foo
    role_session_name: circleci
    configure_default_region: false
    configure_profile_region: true
    region: us-west-2

# ... do something with above creds from foo role

- aws-cli/setup:
    role_arn: bar
    region: us-west-2

# ... do something with above creds from bar role

- run:
    name: aws sts
    command: aws sts get-caller-identity
```

In version 4.1.1, the `aws sts` call shows an ARN using the `bar` role (which is what I expect); in 4.1.2 it shows the `foo` role.  So in 4.1.2 it looks like the first role configuration gets used instead of the second.
