### ISSUE TITLE
Broken AWS Credentials after #164 (4.1.2)

### ISSUE THREAD

**Issue by diranged** [CircleCI-Public/aws-cli-orb#179]
We were testing the upgrade from `4.1.1` to `4.1.2` and all of our builds started to fail even though the Orb itself was succeeding. Our builds were erroring out with `Unable to locate credentials. You can configure credentials by running "aws configure".` errors.

After looking at the changelog and code, I see this very strange pattern  of variables in https://github.com/CircleCI-Public/aws-cli-orb/pull/164:

https://github.com/CircleCI-Public/aws-cli-orb/pull/164/files#diff-051b3bbe8c3d5c209a191b1943048231c395fd687a33b82739cd933ab39b39d1R48-R50

I don't understand why the variables names are changed - but this breaks AWS clients.

**Comment by pheydenrych** [comment]
Sessions established using `aws-cli/assume_role_with_web_identity` also succeed in the orb, but subsequent AWS commands fail with the error `The security token included in the request is invalid.`

**Comment by laupow** [comment]
Another confirmation that 4.1.2 introduced a regression for customers. Pinning the orb to 4.1.1 preserved the existing behavior: `circleci/aws-cli@4.1.1`.

Configuration that broke:

```yaml
          - aws-cli/setup:
              role_arn: "arn:aws:iam::12345678910:role/circleci-run-tests"
              region: "us-east-1"
              role_session_name: "circleci-run-tests"
              session_duration: "3600"
```
<img width="766" alt="Screenshot 2023-11-21 at 9 04 51 AM" src="https://github.com/CircleCI-Public/aws-cli-orb/assets/6674176/f1a87d6e-a088-40fc-968b-1231bc003e4b">

Terraform consumed the AWS access keys. It is now broken on 4.1.2:

<img width="1087" alt="Screenshot 2023-11-21 at 9 04 59 AM" src="https://github.com/CircleCI-Public/aws-cli-orb/assets/6674176/1c116780-a8d9-4927-a610-c17b568e066f">



@KyleTryon @brivu See note about a major regression in the `4.x` branch. Please bundle those changes into a major version.

https://github.com/CircleCI-Public/aws-cli-orb/pull/164/files#r1400772501
