### ISSUE TITLE
/tmp/default.keys: No such file or directory

### ISSUE THREAD

**Issue by LeoAnt02** [CircleCI-Public/aws-cli-orb#189]
When running the orbs I have a pipeline failure 

using   aws-cli: circleci/aws-cli@4.1.2

``/bin/bash: line 11: /tmp/default.keys: No such file or directory``
``Exited with code exit status 1
CircleCI received exit code 1``

config

``` 
....
executor: aws-cli/default
steps: 
  - aws-cli/install
  - aws-cli/setup:
      aws_access_key_id: AWS_ACCESS_KEY_ID
      aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      region: << parameters.region >>
```
