### ISSUE TITLE
[aws-cli/setup] After upgrading from 4.0.0 to 5.1.1, the region is not set correctly anymore

### ISSUE THREAD

**Issue by IgorVanian** [CircleCI-Public/aws-cli-orb#213]
Hi.

I'm using `circleci/aws-s3@4.1.0` orb with env vars in parameters. It was working up until `4.0.0` but starting from `4.1.0` I'm getting this error message:

```
Provided region_name 'S3_REGION' doesn't match a supported format.

Exited with code exit status 255
```

By looking at the changelog, could it be something related to #142 ? I'm not familiar with such configurations.

YAML

```yml
  job-example:
    executor: aws-cli/default
    parameters:
      s3-access-key:
        type: env_var_name
        default: S3_ACCESS_KEY
      s3-secret-key:
        type: env_var_name
        default: S3_SECRET_ACCESS_KEY
      s3-region:
        type: env_var_name
        default: S3_REGION
    steps:
      - aws-cli/setup:
          aws_access_key_id: << parameters.s3-access-key >>
          aws_secret_access_key: << parameters.s3-secret-key >>
          region: << parameters.s3-region >>
      - run:
          command: |
            # List all folders in the S3 bucket and iterate over them
```

Thanks!
