### ISSUE TITLE
AWS CodeArtifact Login failure on 5.2.0

### ISSUE THREAD

**Issue by gscandola** [CircleCI-Public/aws-cli-orb#220]
Hi 👋,

On one of our repository we are using AWS CodeArtifact to store our npm packages. We are using the `aws codeartifact login` command to authenticate with the repository. Since the bump to `5.2.0` this command is failing with the following error:

```
An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.

Exited with code exit status 254
```

Since all of our pipelines worked on `5.1.2` I looked onto the [source code diff](https://github.com/CircleCI-Public/aws-cli-orb/compare/v5.1.2...v5.2.0) between these two versions.

The change in `src/scripts/configure.sh` lead me to check, on CircleCI machine through a SSH Session, the content of `~/.aws/credentials`, since this token issue seems related to credentials and this seems to be the only change that could impact us.

And it seems that the content is different between a pipeline running on `5.1.2` and one running on `5.2.0` :

```
// 5.2.0: cat ~/.aws/credentials

[my-profile]
aws_access_key_id = AWS_ACCESS_KEY_ID_DEV
aws_secret_access_key = AWS_SECRET_ACCESS_KEY_DEV

// 5.1.2 : cat ~/.aws/credentials

[my-profile]
aws_access_key_id = C1V3VPMX914PWAI2W1C0
aws_secret_access_key = 9cIc98qvRoPq801+MQWuDTVkaNVlHjM49C1Me+Q6
```

(Values in the 5.1.2 example are not the real one, I replaced them by random char/digits for this example since it is some sensitive data).

I always struggle to understand how shell/bash env var expand work, moreover when I had some CircleCI magic stuff.

But I suspect the recent removal of `\$` (`\$$AWS_CLI_STR_ACCESS_KEY_ID` -> `$AWS_CLI_STR_ACCESS_KEY_ID`) to lead this issue following [CircleCI documentation](https://discuss.circleci.com/t/new-cli-command-circleci-env-subst/47699).

Here is an partial extract of our CircleCI config file:

(The `AWS_ACCESS_KEY_ID_DEV` and `AWS_SECRET_ACCESS_KEY_DEV` are defined as environment variable in CircleCI Project configuration).

```yml
parameters:
    my_profile_dev_aws_credentials: &my_profile_dev_aws_credentials
    aws_access_key_id: AWS_ACCESS_KEY_ID_DEV
    aws_secret_access_key: AWS_SECRET_ACCESS_KEY_DEV
    profile_name: my-profile-dev
    region: eu-west-1

commands:
    aws_setup:
        description: AWS Setup
        parameters:
            aws_access_key_id:
                description: AWS Access Key ID for authentication
                type: string
            aws_secret_access_key:
                description: AWS Secret Access Key for authentication
                type: string
            profile_name:
                description: Named profile for AWS CLI
                type: string
            region:
                description: AWS Region
                type: string
                default: eu-west-1
        steps:
            - aws-cli/setup:
                  aws_access_key_id: << parameters.aws_access_key_id >>
                  aws_secret_access_key: << parameters.aws_secret_access_key >>
                  profile_name: << parameters.profile_name >>
                  region: << parameters.region >>
            - run:
                  name: Log in to our CodeArtifact
                  command: |
                      aws codeartifact login --tool npm --domain aviv --domain-owner *** --repository *** --namespace **** --profile << parameters.profile_name >>

jobs:
    setup:
        docker: *default_docker
        resource_class: medium
        parameters:
            aws_access_key_id:
                description: AWS Access Key ID for authentication
                type: string
            aws_secret_access_key:
                description: AWS Secret Access Key for authentication
                type: string
            profile_name:
                description: Named profile for AWS CLI
                type: string
            region:
                description: AWS Region
                type: string
                default: eu-west-1
        steps:
            - aws_setup:
                  aws_access_key_id: << parameters.aws_access_key_id >>
                  aws_secret_access_key: << parameters.aws_secret_access_key >>
                  profile_name: << parameters.profile_name >>
                  region: << parameters.region >>
            - checkout
            # some other steps

workflows:
    pull_request_workflow:
        when:
            equal: ['trigger-pull-request', << pipeline.parameters.GHA_Action >>]
        jobs:
            - setup:
                  <<: *my_profile_dev_aws_credentials
            # some other jobs
```

**Comment by marboledacci** [comment]
Hi @gscandola, that version is changing the type of the parameter, it used to be managed as environment variable by default, which caused issues in many places. Now you have to set that explicitly. For that, just add `$` in front of your value.

Your new parameters would be:
```yaml
parameters:
    my_profile_dev_aws_credentials: &my_profile_dev_aws_credentials
    aws_access_key_id: $AWS_ACCESS_KEY_ID_DEV
    aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_DEV
    profile_name: my-profile-dev
    region: eu-west-1
```
