### ISSUE TITLE
Providing `python-version` to the executor

### ISSUE THREAD

**Issue by s4ros** [CircleCI-Public/aws-cli-orb#23]
Hi there!
I have a stupid question about the executor configuration. Regarding this line:
https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/%40orb.yml#L14
... so will anyone be so kind to provide me just a few lines of CirlceCI yaml configuration how to (and where exactly) configure the `python-version` for the aws-cli executor?

I was trying different things but I ended up with yaml syntax error or some other strange stuff.

Thanks in advance!

**Comment by lokst** [comment]
@s4ros It can be specified like this:

```
jobs:
  build:
    executor:
      name: awscli/default
      python-version: "3.7"
    steps:
      - awscli/install
```

Hope the example helps!
