### ISSUE TITLE
Cache "Install AWS CLI" step

### ISSUE THREAD

**Issue by raine** [CircleCI-Public/aws-cli-orb#25]
Is there a way to cache the installation step?

What's the point of using the orb instead of a docker image that has the command built in, if you have to spend 15 seconds installing the tool in every build?

Cheers.

**Comment by Crazometer** [comment]
Alternatively could the default executor come with the cli installed?

**Comment by lokst** [comment]
@raine It might be possible to cache the installation step by caching the Python dependencies installed with `pip`.
@Crazometer Thanks for the suggestion. The default executor is set to one of CircleCI's Python images for users' convenience. Although pre-installing the CLI into the image would make this orb perform faster, we have to consider the tradeoffs for other users of the image who do not use the aws CLI.

**Comment by Crazometer** [comment]
@lokst Not sure how the build process works there - I was thinking more along the lines of you could add a layer to the circleci python image.

**Comment by lokst** [comment]
@Crazometer I understand the importance of reducing your build time 🙂 At the same time we do need to keep the circleci python image as slim as possible in the interests of other users, so I think it's more feasible to enhance the aws-cli orb instead, for example, to cache the python packages. I am adding this as a feature request to our backlog.

**Comment by Crazometer** [comment]
Glad it’s on the backlog.

I think you are misunderstanding me though, the base image for this orb
could be something built on top of the standard python image. Hence non aws
users would not be affected.

**Comment by lokst** [comment]
@Crazometer I understand what you mean. It's a great approach but considering the maintenance upkeep needed for every new convenience image we support, I would recommend filing a suggestion on our Ideas portal on https://ideas.circleci.com/ so that our product team can gauge interest in this 🙂

**Comment by aleyan** [comment]
"Install AWS CLI" across two jobs takes up to 22% of the time in our most common workflow.

Per first comment suggestion, I tried caching via pip and circleci tooling. Unfortunately, aws-cli doesn't get installed in a virtualenv, making caching difficult.
```
orbs:
  aws-cli: circleci/aws-cli@0.1.19

references:
  save_awscli_cache: &save_awscli_cache
    save_cache:
      key: orb-aws-cli-v0_1_19
      paths:
        - /usr/local/lib/python3.7/site-packages
  restore_awscli_cache: &restore_awscli_cache
    restore_cache:
      keys:
        - orb-aws-cli-v0_1_19

  some-job:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7
    steps:
      - *restore_awscli_cache
      - aws-cli/setup
      - *save_awscli_cache
```

This does not work due to the following error:
```
Found a cache from build 12499 at orb-aws-cli-v0_1_19
Size: 28 MiB
Cached paths:
  * /usr/local/lib/python3.7/site-packages
Downloading cache archive...
Validating cache...
Unarchiving cache...
Failed to unarchive cache
Error untarring cache: Error extracting tarball /tmp/cache069355973 : tar: usr/local/lib/python3.7/site-packages/.libs_cffi_backend/libffi-806b1a9d.so.6.0.4: Cannot open: File exists tar:  [elided]
```
Any ideas?
