### ISSUE TITLE
Support no AWS region because S3 works without

### ISSUE THREAD

**Issue by joshunger** [CircleCI-Public/aws-cli-orb#3]
S3 commands don't require an AWS region and default to US East so it isn't necessary to set a region however the orb fails with the following error message -

```
#!/bin/bash -eo pipefail
aws configure set region $AWS_REGION \
--profile default
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
Exited with code 2
```

**Comment by iynere** [comment]
good idea, on it, sorry for delay ! @joshunger

**Comment by iynere** [comment]
@joshunger check the registry or the source here—there's a new param u can use to skip configuring a default region

**Comment by braian125** [comment]
> S3 commands don't require an AWS region and default to US East so it isn't necessary to set a region however the orb fails with the following error message -
> 
> ```
> #!/bin/bash -eo pipefail
> aws configure set region $AWS_REGION \
> --profile default
> usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
> To see help text, you can run:
> 
>   aws help
>   aws <command> help
>   aws <command> <subcommand> help
> aws: error: too few arguments
> Exited with code 2
> ```

Hi @joshunger I have that same error, could you help me to solve it ?, I have consulted the documentation, I have made several attempts and I always get the same

the deploy looks something like this:

```
deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: /home/circleci
      - aws-s3/sync: #invokes the sync command declared in the s3 orb
          from: ./dist/ci2s3
          to: "s3://${S3_BUCKET}"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
```
