### ISSUE TITLE
the orb doesn't seem to install the latest version of a CLI or it doesn't re-install when version is changed in config.yml

### ISSUE THREAD

**Issue by smostovoy** [CircleCI-Public/aws-cli-orb#30]
The command and error are:
 `aws ecs register-task-definition --cli-input-json file://./tmp/task-definition.json --network-mode awsvpc --requires-compatibilities FARGATE --region ********* --family se-dev-2699`
```
Parameter validation failed:
Unknown parameter in containerDefinitions[6]: "firelensConfiguration", must be one of: name, image, repositoryCredentials, cpu, memory, memoryReservation, links, portMappings, essential, entryPoint, command, environment, mountPoints, volumesFrom, linuxParameters, secrets, dependsOn, startTimeout, stopTimeout, hostname, user, workingDirectory, disableNetworking, privileged, readonlyRootFilesystem, dnsServers, dnsSearchDomains, extraHosts, dockerSecurityOptions, interactive, pseudoTerminal, dockerLabels, ulimits, logConfiguration, healthCheck, systemControls, resourceRequirements
```

My setup looks like this:

```
version: 2.1
orbs:
  docker: circleci/docker@0.5.13
  aws-cli: circleci/aws-cli@0.1.19
jobs:
  deploy:
    executor: docker/machine
    steps:
      - aws-cli/setup:
          aws-access-key-id: QA_AWS_ACCESS_KEY_ID
          aws-secret-access-key: QA_AWS_SECRET_ACCESS_KEY
          aws-region: QA_AWS_REGION
     - run: scripts/build
```
scripts/build is creating a TaskDefinition in ECS with a Firelens a log adapter. This new AWS option didn't work untill I added `- run: pip install --upgrade awscli` before it. Before that I had a version 0.1.18 of the orb and it was changed to 0.1.19 and nothing changed.
