### ISSUE TITLE
aws-cli/install is failing with cert error

### ISSUE THREAD

**Issue by corydorning53** [CircleCI-Public/aws-cli-orb#55]
I've included the orb and I'm attempting to install but I'm receiving the error below. Everything worked fine until the last 3 builds i attempted:
```
AWS is not installed
Linux ffef583ffef5 4.15.0-1077-aws #81-Ubuntu SMP Wed Jun 24 16:48:15 UTC 2020 x86_64 GNU/Linux
curl: (51) SSL: no alternative certificate subject name matches target host name 'awscli.amazonaws.com'

Exited with code exit status 51
```

config.yml
```
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
...
jobs:
  package-artifact:
    docker:
      - image: circleci/node:12.18
    working_directory: *workspace
    steps:
      - aws-cli/install
```
