### ISSUE TITLE
role_arn can not be used without static credentials

### ISSUE THREAD

**Issue by daniel-ciaglia** [CircleCI-Public/aws-cli-orb#57]
The newly introduced `setup` parameter `role_arn` can only be used together with static credentials to assume the role.
See: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html -> `role_arn`

This is not possible with the Orb right now as neither `credential_source` nor `source_profile` can be configured.

I worked around that by these steps, which create a `default` profile with credentials, a named profile `codeartifact` with a `role_arn` setting and finally I add the `source_profile` to be `default` to retrieve the static credentials.
Please note that all AWS commands have to have the `--profile codeartifact` parameter later on (missing from the docs).

```
    steps:
      - aws-cli/setup
      - aws-cli/setup:
          profile-name: codeartifact
          role-arn: "arn:aws:iam::0123456789:role/foo-bar"
      - run:
          name: fix aws cli setup
          command: aws configure set profile.codeartifact.source_profile default
      - run:
          name: Codeartifact login
          command: >
            aws codeartifact login
            --profile codeartifact
```

# options
## `credential_source`
The only possible value would be `Environment` – Specifies that the AWS CLI is to retrieve source credentials from environment variables.
But this renders the writing of credentials to the `~/.aws/credentials` file useless

## `source_profile`
better option where logic must be added to the orb to
- detect that a `profile-name` is to be used
- apply credentials to the `default` profile
- create the `profile-name` profile wo/ credentials
- reference the `default` profile as `source_profile`

WDYT?

**Comment by triqi** [comment]
I think introducing a new step `aws-cli/assume-role` would work well.

```
steps:
    - aws-cli/setup # Configure the default profile
    - aws-cli/assume-role: # Configure the assume role profile
        profile-name: codeartifact
        role-arn: "arn:aws:iam::0123456789:role/foo-bar"
```

The above `aws-cli/assume-role` step would be the equivalent to something below.

```
- run:
    name: Configure AWS Assume Role
    command: |-
        aws configure set profile.$PARAM_AWS_CLI_PROFILE_NAME.role_arn "$PARAM_AWS_CLI_ROLE_ARN"
        aws configure set profile.$PARAM_AWS_CLI_PROFILE_NAME.source_profile default
```
