### ISSUE TITLE
Can't use ENV VARS to dynamically pass profile-name to setup command

### ISSUE THREAD

**Issue by ahasna** [CircleCI-Public/aws-cli-orb#85]
recently upgraded to the latest orb version and started having issues with passing profile name using an environment variable stored in CircleCI Context.

my config:

```yml
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  deploy:
    steps:
      - aws-cli/install
      - aws-cli/setup:
          profile-name: $DEPLOY_PROFILE_NAME 
```
when I rerun the job with SSH enabled and I run `cat ~/.aws/config` I get this: 
```text
[default]
region = us-east-1
[profile $DEPLOY_PROFILE_NAME]
region = us-east-1
```
this used to work with `v0.1.13` of the Orb which is no longer supported due to Python 2.7 depreciation by AWS CLI.

is there any workarounds/better approaches/solution to this issue?
