### ISSUE TITLE
`aws eks` missing when running job and `aws --version mismatch`

### ISSUE THREAD

**Issue by phil-lgr** [CircleCI-Public/aws-cli-orb#9]
A minimal config:

```yaml
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
  aws-ecr: circleci/aws-ecr@4.0.1
  helm: circleci/helm@0.1.0
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - aws_cli_setup
      - build_test_deploy:
          requires: 
            - aws_cli_setup
jobs:
  build_test_deploy:
    machine: 
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: aws --version
      - run: aws eks update-kubeconfig --name erp-app-cluster
      - helm/install-helm-client
      - run: helm list
  aws_cli_setup:
    working_directory: ~/repo
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - aws-cli/configure:
          profile-name: circle-ci
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - aws-ecr/ecr-login:
          region: AWS_REGION      
```

the `aws_cli_setup` job completes but when I run `aws eks` I get:

`Invalid choice: 'eks', maybe you meant:`

I don't understand why `aws eks` is not available with that version of the aws cli...

in the other job, `build_test_deploy`, `- run: aws --version` reports a different version, I don't get it :(

![image](https://user-images.githubusercontent.com/9644867/57243972-600b2000-7005-11e9-8c36-2c0380186b0f.png)
