### ISSUE TITLE
Support for external_id for assumed role

### ISSUE THREAD

**Issue by BDBI-Duncan** [CircleCI-Public/aws-cli-orb#90]
Add external_id for aws-cli/setup.
```
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
          role-arn: $ROLE_ARN
          external_id: $EXTERNAL_ID
      - run: aws sts get-caller-identity "This should return the assumed role as defined by role-arn which requires the external_id"
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
```
